### ISSUE TITLE
运行image_process.py报错

### ISSUE THREAD

**Issue by zhougeAI** [jiangnanboy/pdf_to_docx#1]
AttributeError: 'Document' object has no attribute 'pageCount'

Traceback (most recent call last):
  File "C:\Users\Chenlz\Desktop\pdf_to_docx\src\pdf_doc\pdf_recovery_doc.py", line 121, in <module>
    pdf2doc(pdf_path)
  File "C:\Users\Chenlz\Desktop\pdf_to_docx\src\pdf_doc\pdf_recovery_doc.py", line 35, in pdf2doc
    pdf_image(pdf_file, image_path)
  File "C:\Users\Chenlz\Desktop\pdf_to_docx\src\util\image_process.py", line 15, in pdf_image
    for pg in range(pdf_doc.pageCount):
AttributeError: 'Document' object has no attribute 'pageCount'

**Comment by zhougeAI** [comment]
问题找到了，是新版本的fitz库的方法发生了变化，应该改为page_count
